### ISSUE TITLE
CI - Add Code Climate and README badges

### ISSUE THREAD

**Issue by ctsstc** [BendJS/bend-community-site#17]
Add Code Climate, Code Coverage Analysis, and README.md badges.

## Add
- [x] Code Climate CI
  - [x] Travis pushes to CC for code coverage
- [x] README badges

**Comment by ctsstc** [comment]
Blocked by #13

**Comment by russtaylor** [comment]
This is now ready to be worked on. It looks like we need Code Climate enabled for the organization (BendJS) before it can be enabled for this repo. @ctsstc or @kcloud99, could one of you activate it for the org? If you want to, you can also enable it for this repo. Instructions are here: https://docs.codeclimate.com/docs/approve-code-climate-as-a-third-party-application-in-github

I'm going to start adding the badges to the README (and putting some non-generic content in the README, too).

**Comment by russtaylor** [comment]
Ah, scratch that! It looks like it's already enabled. 😀

**Comment by ahtee** [comment]
Are you taking this @russtaylor ?

**Comment by russtaylor** [comment]
Yup!
