### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kcloud99** [BendJS/bend-community-site#5]
Create testing strategy and implement framework and useful packages to get started. Write basic documentation about how the testing will work.

**Comment by ctsstc** [comment]
Hyper interested in this one 👥

**Comment by abell95** [comment]
Can lend a hand here

**Comment by ctsstc** [comment]
## Tasks

- [ ] Install Jest
- [ ] Add documentation for running tests

**Comment by JacobMGEvans** [comment]
I might take a whack at this too, utilizing Jest and react-testing-library

**Comment by ctsstc** [comment]
We determined with the react create app that Jest came pre-installed, as well as documentation that was already in place.

The focus has been to close this and work on #13 for CI work.

**Comment by JacobMGEvans** [comment]
Yes, it does have Jest under the hood, Babel, webpack, and more... I actually added a feature to create react app that will allow for profiling of the application in production build with a flag ` yarn build --profile `

**Comment by JacobMGEvans** [comment]
Good for performance and testing 😁

**Comment by ascasson** [comment]
@ctsstc @JacobMGEvans @ccrossleyCBT Is this done?

**Comment by JacobMGEvans** [comment]
It's scaffolding mainly... So yes, I was aiming at just getting some balls
rolling not finishing any of them in particular lol 😆
